version: '3.1'

services:
  minesweeper-game:
    image: mine-sweeper-game:local
    build:
      context: .
      dockerfile: minesweeper-game/Dockerfile
    env_file: .env
    ports:
      - "8080:8080"
    depends_on:
      - mongo

  mongo:
    image: mongo:4.0
    ports:
      - "27017:27017"

  minesweeper-otherservice:
    image: mine-sweeper-otherservice:local
    build:
      context: .
      dockerfile: minesweeper-otherservice/Dockerfile
    env_file: .env
    ports:
      - "8081:8080"
