version: '3.1'

services:
  app:
    image: mine-sweeper:local
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    ports:
      - "8080:8080"
    depends_on:
      - mongo


  mine-sweeper-ci:
    image: mine-sweeper-ci
    build:
      context: .
      dockerfile: gradle.Dockerfile
    command: ["gradle", "--info" ,"--no-daemon", "bootRun"]
    env_file: .env
    ports:
      - "8080:8080"
    depends_on:
      - mongo

  mongo:
    image: mongo:4.0
    ports:
      - "27017:27017"