apiVersion: v1
kind: Service
metadata:
  name: minesweeper-front
  labels:
    app: minesweeper
spec:
  selector:
    app: minesweeper
  ports:
    - name: http
      port: 8080
      targetPort: 8080
