apiVersion: apps/v1
kind: Deployment
metadata:
  name: minesweeper-otherservice
  labels:
    app: minesweeper-otherservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minesweeper-otherservice
  template:
    metadata:
      labels:
        app: minesweeper-otherservice
    spec:
      containers:
        - name: mine-sweeper-otherservice
          image: mine-sweeper-otherservice:1.0.0
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: prod
