apiVersion: v1
kind: Service
metadata:
  name: minesweeper-otherservice-srv
  labels:
    app: minesweeper-otherservice
spec:
  selector:
    app: minesweeper-otherservice
  ports:
    - name: http
      port: 80
      targetPort: 8080
